using System;

using BillingFlow.Domain.Enums;

using FluentMigrator;

namespace BillingFlow.Migrations.Schema.Seeds;

[Migration(202605020505)]
public class SeedAdminUser : Migration
{
    // 1. Stable Identity: Deterministic GUID ensures consistency across Up/Down methods
    private static readonly Guid AdminId = Guid.Parse("00000000-0000-0000-0000-000000000001");

    public override void Up()
    {
        // 2. Deterministic startup date instead of 'DateTimeOffset.UtcNow'
        var createdAt = new DateTimeOffset(2026, 5, 2, 0, 0, 0, TimeSpan.Zero);

        // 3. Hash Verification: This is a BCrypt hash (Work Factor 11).
        // Verify that this exact hash matches the password "Admin@1234" 
        // generated by our IPasswordHasher implementation.
        const string adminPasswordHash = "$2a$12$UQ6DLTv9nYIK3Igqck27duSF.gdDcWmRnfcJkAEIoZ2GEhQGViG2i";

        // 4. Idempotency and Explicit Domain Mapping
        // Using a raw SQL guard clause prevents Primary Key violations if the migration 
        // is run multiple times against a partially prepared environment.
        Execute.Sql($@"
            IF NOT EXISTS (SELECT 1 FROM Users WHERE Id = '{AdminId}')
            BEGIN
                INSERT INTO Users (Id, Email, PasswordHash, Role, Status, CreatedAt)
                VALUES (
                    '{AdminId}', 
                    'admin@billingflow.com', 
                    '{adminPasswordHash}', 
                    {(int)Role.Admin}, 
                    {(int)UserStatus.Active}, 
                    '{createdAt:O}'
                );
            END
        ");
    }

    public override void Down()
    {
        // 5. Deletion by stable ID (resilient to email modifications during the app's lifecycle)
        Delete.FromTable("Users")
            .Row(new { Id = AdminId });
    }
}
